background #0b0e14
foreground #e5e1cf
cursor #f19618
selection_background #2d4157
selection_foreground #ffffff
color0 #141820
color8 #677587
color1 #ff3333
color9 #ff6565
color2 #b8cc52
color10 #e9fe83
color3 #e6c446
color11 #fff778
color4 #399ee6
color12 #68d4ff
color5 #c79bf4
color13 #dfbfff
color6 #95e5cb
color14 #c7fffc
color7 #c9c7be
color15 #ffffff
