[helpers]

[default]
depends = []

[bash.files]
"bash/.bashrc" = "~/.bashrc"
#"bash/.bash_profile" = "~/.bash_profile"

[fish.files]
"fish/config.fish" = "~/.config/fish/config.fish"

[git.files]
"git/.gitconfig" = "~/.gitconfig"
"git/.gitmessage" = "~/.gitmessage"

[gnome-shell.files]
"gnome-shell/.themes" = "~/.themes"

[gnome-shell-extensions.files]
"gnome-shell/extensions" = {target = "~/.local/share/gnome-shell/extensions", type = "symbolic"}

[grub.files]
"grub/themes" = "/boot/grub/themes"
"grub/grub" = "/etc/default/grub"

[kitty.files]
"kitty" = { target = "~/.config/kitty", type = "symbolic" }

[neofetch.files]
"neofetch/config.conf" = "~/.config/neofetch/config.conf"

[neovim.files]
"neovim/NvChad" = {target = "~/.config/nvim/", type = "symbolic"}
"neovim/custom" = {target = "~/.config/nvim/lua/custom/", type = "symbolic"}

[zsh.files]
"zsh/.zshrc" = "~/.zshrc"
"zsh/.zsh" = {target = "~/.zsh", type = "symbolic"}

[nushell.files]
"nushell/config.nu" = "~/.config/nushell/config.nu"

[powershell-linux.files]
"powershell" = "~/.config/powershell"

[starship.files]
"starship/starship.toml" = "~/.config/starship.toml"

[keyd.files]
"keyd/default.conf" = "/etc/keyd/default.conf"

[helix.files]
"helix/" = "~/.config/helix/"

[atuin.files]
"atuin" = "~/.config/atuin"

[yazi.files]
"yazi" = "~/.config/yazi/"

[tmux.files]
"tmux/tmux.conf" = "~/.config/tmux/tmux.conf"
"tmux/tpm" = "~/.tmux/plugins/tpm"
