[helpers]

[default]
depends = []

[bash.files]
"bash/.bashrc" = "~/.bashrc"
#"bash/.bash_profile" = "~/.bash_profile"

[fish.files]
"fish/completions" = "~/.config/fish/completions"
"fish/conf.d" = "~/.config/fish/conf.d"
"fish/functions" = {target = "~/.config/fish/functions", type = "symbolic" }
"fish/config.fish" = "~/.config/fish/config.fish"
"fish/fish_plugins" = "~/.config/fish/fish_plugins"
"fish/fish_variables" = "~/.config/fish/fish_variables"

[git.files]
"git/.gitconfig" = "~/.gitconfig"
"git/.gitmessage" = "~/.gitmessage"

[gnome-shell.files]
"gnome-shell/.themes" = "~/.themes"

[gnome-shell-extensions.files]
"gnome-shell/extensions" = {target = "~/.local/share/gnome-shell/extensions", type = "symbolic"}

[grub.files]
"grub/themes" = "/boot/grub/themes"
"grub/grub" = "/etc/default/grub"

[kitty.files]
"kitty/kitty-themes" = {target = "~/.config/kitty/kitty-themes", type = "symbolic"}
"kitty/kitty.conf" = { target = "~/.config/kitty/kitty.conf", type = "symbolic" }

[neofetch.files]
"neofetch/config.conf" = "~/.config/neofetch/config.conf"

[neovim.files]
"neovim/lua" = "~/.config/nvim/lua"
"neovim/init.lua" = "~/.config/nvim/init.lua"
"neovim/lazy-lock.json" = "~/.config/nvim/lazy-lock.json"

[zsh.files]
"zsh/.zshrc" = "~/.zshrc"

[nushell.files]
"nushell" = "/.config/nushell"

[powershell-linux.files]
"powershell" = "/.config/powershell"
