# An array of the names of all packages that are selected.
# Only the files and variables that belong to packages in this list are kept.
# Note that in this example, the `graphics` package is automatically added as well.
includes = []

packages = [
    "bash",
    "fish",
    "git",
    "kitty",
    "neofetch",
    "neovim",
    "zsh",
    "nushell",
    "powershell-linux",
    "starship",
    "helix"
]

[files]

[variables]
